account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [

    path('register/', views.register, name='register'),
    path('profile_edit', views.edit, name='profile_edit'),
    path('profile/', views.profile, name='profile'),
    path('delete_user/<int:user_id>/', views.delete_user, name='confirm_delete_user'),
    path('all_users/', views.all_users, name='all_users'),
    path('follow/', views.user_follow, name='user_follow'),
    path('profile/<str:username>/', views.view_profile, name='view_profile'),
    path('most_followed_users/', views.most_followed_users, name='most_followed_users'),
    path('followed_users/', views.followed_users, name='followed_users'),
    path('activity_feed/', views.activity_feed, name='activity_feed'),
    path('all_messages/', views.all_messages, name='all_messages'),
    path('user_messages/<str:username>/', views.user_messages, name='user_messages'),
    path('send_messages/<str:username>/', views.send_messages, name='send_messages'),
    path('confirm_delete_messages/<str:username>/', views.user_messages_delete, name='confirm_delete_messages'),
    path('confirm_delete_messages/<str:username>/', views.user_messages_delete, name='confirm_delete_messages'),
    path('', include('django.contrib.auth.urls')),

]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from learning_logs.sitemaps import TopicSitemap

sitemaps = {
    'topics': TopicSitemap,
}

urlpatterns = [

    path('rex_pex_fex/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('learning_logs.api.urls', namespace='api')),
    path('account/', include('account.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('learning_logs.urls', namespace='learning_logs')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


topic_router = routers.DefaultRouter()
topic_router.register(r'', views.TopicViewSet, basename='topic')

app_name = 'api'

urlpatterns = [
    path('follow/<int:pk>/', views.UserFollowView.as_view(), name='user_follow'),
    path('most_liked_topics/', views.MostLikedTopics.as_view(), name='most_liked_topics'),
    path('my_profile/', views.MyProfileViewSet.as_view(), name='my_profile'),
    path('user_profile/<int:pk>/', views.UserProfile.as_view(), name='user_profile'),
    path('followed_profiles/', views.FollowedUsers.as_view(), name='followed_profiles'),
    path('', include(topic_router.urls)),

]

learning_logs/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = 'learning_logs'

urlpatterns = [
    path('all_topics/', views.all_topics, name='all_topics'),
    # Page show all topics
    path('topics/', views.topics, name='topics'),
    path('tag/<slug:tag_slug>/', views.all_topics, name='topic_list_by_tag'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Adding new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # adding new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # editing the topic
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    # delete topic
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='confirm_delete_topic'),
    # delete comment
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='confirm_delete_entry'),
    # share
    path('<int:topic_id>/share/', views.share_post, name='share_post'),
    # search
    path('search/', views.topic_search, name='topic_search'),
    # topic like
    path('like/', views.topic_like, name='like'),
    # most liked topics
    path('most_liked_topics/', views.most_liked_topics, name='most_liked_topics'),
    # ranking topics
    path('most_viewed/', views.most_viewed, name='most_viewed'),
    # liked topics
    path('liked_topics/', views.liked_topics, name='liked_topics'),
    # api page
    path('api_page/', views.api_page, name='api_page'),
    # privacy policy
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    # contact
    path('contact/', views.contact_view, name='contact'),
    path('contact/success/', views.success_view, name='contact_success'),


    # Home page
    path('', views.index, name='index'),

]

learning_logs/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from autoslug import AutoSlugField
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.conf import settings


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


class Topic(models.Model):
    text = models.CharField(max_length=250)
    body = models.TextField(blank=True)
    slug = AutoSlugField(populate_from='text', max_length=250, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = TaggableManager(blank=True)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='topic_liked', blank=True)
    total_likes = models.PositiveIntegerField(default=0)
    total_views = models.PositiveIntegerField(default=0)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-date_added']
        indexes = [
            models.Index(fields=['-date_added']),
            models.Index(fields=['-total_likes']),
        ]

    def get_absolute_url(self):
        return reverse('learning_logs:topic', args=[str(self.id)])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.text)
        super().save(*args, **kwargs)



    def __str__(self):
        """Return a string representation of a model"""
        return self.text


class Entry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, related_name='entries', on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']
        indexes = [
            models.Index(fields=['-date_added']),
        ]

    def __str__(self):
        return f'{self.text[:50]}...'

learning_logs/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'body', 'tags']
        labels = {'text': '',
                  'body': '',
                  'tags': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class EmailPostForm(forms.Form):
    # name = forms.CharField(max_length=25)
    # email = forms.EmailField(max_length=25)
    to = forms.EmailField()
    # comments = forms.CharField(required=False, widget=forms.Textarea)


class SearchForm(forms.Form):
    search = forms.CharField()


class ContactForm(forms.Form):
    subject = forms.CharField(label='Subject', max_length=100, required=True)
    email = forms.EmailField(label='Sender email', required=True)
    message = forms.CharField(label='Message', widget=forms.Textarea, required=True)

learning_logs/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics, status, viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from django.db.models import Count
from learning_logs.models import Topic, Entry
from learning_logs.api.serializers import TopicSerializer, TopicsSerializer, ProfileSerializer
from account.models import Profile


class TopicListView(generics.ListAPIView):
    queryset = Topic.objects.all()
    serializer_class = TopicsSerializer
    pagination_class = PageNumberPagination


class TopicDetailView(generics.RetrieveAPIView):
    queryset = Topic.objects.all()
    serializer_class = TopicSerializer


class UserFollowView(APIView):
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, pk, format=None):
        profile = get_object_or_404(Profile, pk=pk)
        if request.user.pk == profile.user.pk:
            return Response({'error': 'You can not follow yourself'}, status=status.HTTP_400_BAD_REQUEST)
        elif request.user in profile.user_follow.all():
            return Response({'error': 'You are already following this user'}, status=status.HTTP_400_BAD_REQUEST)

        profile.user_follow.add(request.user)
        return Response({'success': True, 'message': 'Enrolled successfully'})


class TopicViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Topic.objects.all()
    serializer_class = TopicSerializer


class MyProfileViewSet(APIView):
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = Profile.objects.all()

    def get(self, request):
        profile = get_object_or_404(Profile, user=request.user)
        serializer = ProfileSerializer(profile)

        # Include topics in the response
        topics = Topic.objects.filter(owner=request.user)
        topic_serializer = TopicSerializer(topics, many=True)

        data = {
            'profile': serializer.data,
            'topics': topic_serializer.data,
        }

        return Response(data)


class UserProfile(APIView):
    queryset= Profile.objects.all()

    def get(self, request, pk):
        profile = get_object_or_404(Profile, user__pk=pk)
        topics = Topic.objects.filter(owner=profile.user)

        topic_serializer = TopicSerializer(topics, many=True)
        profile_serializer = ProfileSerializer(profile)

        data = {
            'profile': profile_serializer.data,
            'topics': topic_serializer.data,
        }

        return Response(data)

class FollowedUsers(APIView):
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = Profile.objects.all()

    def get(self, request):
        user_profile = get_object_or_404(Profile, user=request.user)
        followed_profiles = user_profile.user_follow.all()
        serializer = ProfileSerializer(followed_profiles, many=True)
        data = {'followed_users': serializer.data}
        return Response(data)


class MostLikedTopics(APIView):
    permission_classes = []

    def get(self, request, *args, **kwargs):
        """
        Get the most liked topics.
        """
        topics = Topic.objects.annotate(likes_count=Count('total_likes')).order_by('-likes_count')[:10]
        serializer = TopicSerializer(topics, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


learning_logs/templates/learning_logs/api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Documentation</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <style>
        body {
            padding: 20px;
            background-color: #F0FFF0;
        }

        h3, h5 {
            color: #0078d4;
        }

        code {
            background-color: #e6e6e6;
            padding: 2px 4px;
            border: 1px solid #d1d1d1;
            border-radius: 4px;
        }

        .api-section {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <a href="{% url 'learning_logs:index' %}" class="btn btn-outline-primary float-right">Main Page</a>
    <h3>API Documentation</h3>
    <div class="api-section">
        <h5>Access to All Topics</h5>
        <p>To access all topics, make a GET request to the following endpoint: <code>/api/</code></p>
    </div>
    <div class="api-section">
        <h5> Access to Most Liked Topics</h5>
    <p>
        To access the most liked topics, make a GET request to the following endpoint: <code>/api/most_liked_topics/</code>
    </p>
    </div>
    <div class="api-section">
    <h5> Access to Each Topic Individually</h5>
    <p>
        To access a specific topic, replace {topic_id} with the topic's ID in the following endpoint: <code>/api/{topic_id}/</code>
    </p>
    </div>
    <div class="api-section">
    <h5> Follow User (For Authenticated Users)</h5>
    <p>
        Note: Authentication is required for this endpoint.
    </p>
    <p>
        To follow a user, make a <strong>POST</strong> request to the following endpoint: <code>/api/follow/{user_id}/</code>
    </p>
    </div>
    <div class="api-section">
    <h5> My profile(For Authenticated Users)</h5>
    <p>
        Note: Authentication is required for this endpoint.
    </p>
    <p>
        To access personal profile, make a POST request to the following endpoint: <code>/api/my_profile/</code>
    </p>
    </div>
    <div class="api-section">
    <h5> Followed profiles(For Authenticated Users)</h5>
    <p>
        To acces user profile, make a POST request to the following endpoint: <code>/api/followed_profiles/</code>
    </p>
    </div>
    <div class="api-section">
    <h5> User profile</h5>
    <p>
        To acces user profile, make a POST request to the following endpoint:
        <code>/api/user_profile/{user_id}/</code>
    </p>
    </div>
</body>
</html>

learning_logs/templates/learning_logs/confirm_delete_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <div class="container mt-4">
    <div class="card">
      <div class="card-header bg-primary text-white">
        <h4 class="mb-0">Confirm Deletion</h4>
      </div>
      <div class="card-body">
        <p>Are you sure you want to delete your comment? "{{ entry.text }}"?</p>
        <form method="post">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit">Delete</button>
          <a href="{% url 'learning_logs:topics' %}" class="btn btn-secondary">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

learning_logs/templates/learning_logs/contact_success.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Success</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            color: #343a40;
            text-align: center;
            margin: 50px;
        }

        h1 {
            color: #28a745;
            margin-bottom: 20px;
        }

        p {
            font-size: 18px;
            margin-bottom: 30px;
        }

        .return-btn {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
            background-color: #28a745;
            color: #fff;
            border: 2px solid #28a745;
            border-radius: 5px;
            cursor: pointer;
        }

        .return-btn:hover {
            background-color: #218838;
            border-color: #218838;
        }
    </style>
</head>
<body>
    <h1>Thank you for contacting me!</h1>
    <p>I'll get back to you as soon as possible.</p>
    <a href="{% url 'learning_logs:index' %}" class="return-btn">Return to Main Page</a>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <p>Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  <div class="col-md-6 offset-md-3">
    <div class="card mt-5 p-4">
      <p>Edit:</p>

      <form action="{% url 'learning_logs:edit_topic' topic.id %}" method='post'>
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.text.id_for_label }}">Title:</label>
          {{ form.text }}
        </div>

        <div class="form-group">
          <label for="{{ form.tags.id_for_label }}">Tags:</label>
          {{ form.tags }}
        </div>

        <div class="form-group">
          <label for="{{ form.body.id_for_label }}">Text:</label>
          {{ form.body }}
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-3d">Save</button>
        </div>
      </form>
    </div>
  </div>

  <style>
    .btn-3d {
      background-color: #4c8efc;
      border: 1px solid #2e64e8;
      border-radius: 5px;
      padding: 10px 20px;
      color: #fff;
      font-weight: bold;
      text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
      box-shadow: 0 2px 0 rgba(0, 0, 0, 0.3), 0 3px 6px rgba(0, 0, 0, 0.15),
        inset 0 1px 0 rgba(255, 255, 255, 0.25);
    }

    .btn-3d:hover {
      background-color: #3b7ae4;
      border-color: #1e4adb;
    }

    .btn-3d:active {
      background-color: #3867d6;
      border-color: #0b2f7b;
      box-shadow: 0 1px 0 rgba(0, 0, 0, 0.3), 0 2px 4px rgba(0, 0, 0, 0.15),
        inset 0 1px 0 rgba(255, 255, 255, 0.25);
    }

    .card {
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      margin-top: -45px;
      width: 150%;
    }

    .form-group textarea {
      font-size: 16px;
      padding: 10px;
      border-radius: 5px;
      border: 1px solid #ccc;
      width: 100%;
      box-sizing: border-box;
    }
  </style>

{% endblock content %}

learning_logs/templates/learning_logs/email_sent.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h5>Email Sent</h5>
  <p>Topic: {{ topic.text }}</p>
  <p>Body: {{ topic.body }}</p>
  <p>Recipient: {{ form.cleaned_data.to }}</p>
  <a href="{% url 'learning_logs:index' %}" class="btn btn-outline-success">main page</a>
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<style>
  .card {
    border: 2px solid #0078d4;
    border-radius: 10px;
    margin-bottom: 20px;
  }

  .section-icon {
    margin-right: 8px;
  }

  .login-form input[type="submit"] {
    background-color: #0078d4;
    color: #fff;
    border: none;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 25px;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
    transition: background-color 0.3s, transform 0.2s;
  }

  .login-form input[type="submit"]:hover {
    background-color: #005fa1;
    transform: scale(1.05);
  }

  .social {
    margin-top: 20px;
  }

  .social .facebook,
  .social .google {
    background-color: #4da6ff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 25px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    cursor: pointer;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
    transition: background-color 0.3s, transform 0.2s;
  }

  .social .facebook:hover,
  .social .google:hover {
    background-color: #0080ff;
    transform: scale(1.05);
  }

  #skillsCollapse {
    background-color: #F0FFF0;
    border-radius: 5px;
    padding: 10px;
    margin-top: 10px;
  }

  #skillsCollapse ul {
    list-style-type: none;
    padding: 0;
  }

  #skillsCollapse ul li {
    margin-bottom: 5px;
  }
  .card {
    border: 2px solid #0078d4;
    border-radius: 10px;
    margin-bottom: 20px;
  }

  .card-body {
    padding: 20px;
    background-color: #F0FFF0;
  }

  .section-icon {
    margin-right: 8px;
  }

</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofP+NM6L5tMyi6eTk9L6ZsF86dIHNDz0N" crossorigin="anonymous">

{% if user.is_authenticated %}
  <div class="jumbotron">
    <h2 class="display-3">Welcome, {{ user.username }}!</h2>
    <p class="lead">You are already logged in.</p>
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">My content &raquo;</a>
  </div>
{% else %}
  <div class="container mt-5">
    <div class="row">      
      <div class="col-md-8">
        <div class="row">

          <div class="col-md-6">
              <i class="fas fa-user-plus section-icon"></i>
              <a class="btn btn-primary mt-3 mb-3" href="{% url 'account:register' %}">Register</a>
          </div>
          <div class="col-md-6 text-right">
              <i class="fab fa-facebook section-icon"></i>
              <a class="btn btn-outline-primary mt-3 mb-3" href="{% url 'social:begin' 'facebook' %}">Facebook Sign In</a>

              <i class="fab fa-google section-icon"></i>
              <a class="btn btn-outline-danger mt-3 mb-3" href="{% url 'social:begin' 'google-oauth2' %}">Google Sign In</a>
          </div>

        <div class="col-md-8">
          <div class="container-fluid pt-2">          
            <i class="fas fa-cogs section-icon"></i>
            <div class="dropdown">
              <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown">

                <i class="fas fa-list-ul section-icon"></i> Features
              </button>
              <div class="dropdown-menu">
                <span class="dropdown-item-text">
                  - Account management<br>
                  - Facebook and Google authentication<br>
                  - Pagination<br>
                  - Infinite scroll<br>
                  - Sitemaps<br>
                  - Python-Decouple<br>
                  - Share posts via email<br>
                  - Tagging<br>
                  - Retrieve similar posts<br>
                  - Search by weighted queries<br>
                  - Like feature<br>
                  - Most liked posts<br>
                  - View count<br>
                  - Most viewed posts<br>
                  - Most commented posts<br>
                  - Follow feature<br>
                  - User-to-User messaging feature<br>
                  - Activity stream<br>
                  <hr>
                  - Django Rest Framework features:
                    <ul>
                    - Explore all posts<br>
                    - Access most liked posts<br>
                    - Get individual post<br>
                    - Follow user<br>
                    - View personal profile<br>
                    - View followed users with posts<br>
                    - View specific user with posts<br>
                    </ul>
                  <hr>
                  - AWS Integration:
                    <ul>
                      - AWS RDS for PostgreSQL for secure and scalable database infrastructure<br>
                      - Amazon S3 for reliable storage of static files and user media<br>
                      - Improved performance and scalability with AWS services<br>
                      - Automated backup and recovery options for data protection<br>
                      <hr>
                    </ul>
                </span>
              </div>
            </div>
            <p>Please note: Facebook/Google auth in testing mode. For sign-in application takes username/name/email
              fields for account creation.
              The account can be deleted from the Profile page. More info:</p>
              <p>
                <a class="nav-link" href="{% url 'learning_logs:privacy_policy' %}">Privacy policy</a>
              </p>        
            
            
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %}

learning_logs/templates/learning_logs/most_liked_topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Most Liked Topics</h1>
{% endblock %}

{% block content %}
  <div id="topic-list">
    {% for topic in most_liked_topics %}
      <div class="topic-item">
        <h5><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }}</a></h5>
        <p>By: <a href="{% url 'account:view_profile' topic.owner.username %}" class="text-primary">{{ topic.owner.username }}</a></p>
        <p>Liked: {{ topic.total_likes }}</p>
        <p>{{ topic.body|truncatewords:50 }}</p>
      </div>
    {% endfor %}
  </div>

  <style>
    .topic-item {
      background: #f8f9fa;
      padding: 10px;
      border: 1px solid #d1d1d1;
      border-radius: 10px;
      box-shadow: 3px 3px 6px 0 rgba(0, 0, 0, 0.1);
      margin-bottom: 10px;
    }
  </style>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
  {% if tag %}
    <h3>Posts tagged with "{{ tag.name }}"</h3>
  {% endif %}
{% endblock %}

{% block content %}
  <p><a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">Add discuss</a></p>
  <div class="row">
    {% for topic in topics %}
      <div class="col-md-12 mb-3">
        <div class="topic-item">
          <h5>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
          </h5>
          <p class="tags">
            Tags:
            {% for tag in topic.tags.all %}
              <a href="{% url 'learning_logs:topic_list_by_tag' tag.slug %}">
                <span class="badge badge-secondary">{{ tag.name }}</span>
              </a>
              {% if not forloop.last %}, {% endif %}
            {% endfor %}
             <strong>
                <div class="topic-info">
                  <div>
                    <span class="count">
                      <span class="total">{{ topic.total_likes }}</span>
                      {% if total_likes == 1 %}
                        <i class="fas fa-thumbs-up"></i> like
                      {% else %}
                        <i class="fas fa-thumbs-up"></i> likes
                      {% endif %}
                    </span>
                  </div>
                </div>
              </strong>
          </p>
          <div class="btn-group">
            <a href="{% url 'learning_logs:edit_topic' topic.id %}" class="btn btn-secondary btn-sm" role="button">Edit</a>
            <a href="{% url 'learning_logs:confirm_delete_topic' topic_id=topic.id %}" class="btn btn-danger btn-sm" role="button">Delete</a>
          </div>
        </div>
      </div>
    {% empty %}
      <p class="col-md-12">Add some more.</p>
    {% endfor %}
    {% include 'learning_logs/pagination.html' with page=topics %}
  </div>
  <style>
    .topic-item {
      background: #f8f9fa;
      padding: 10px;
      border: 1px solid #d1d1d1;
      border-radius: 10px;
      box-shadow: 3px 3px 6px 0 rgba(0, 0, 0, 0.1);
    }
  </style>
{% endblock content %}