account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [

    path('register/', views.register, name='register'),
    path('profile_edit', views.edit, name='profile_edit'),
    path('profile/', views.profile, name='profile'),
    path('delete_user/<int:user_id>/', views.delete_user, name='confirm_delete_user'),
    path('all_users/', views.all_users, name='all_users'),
    path('follow/', views.user_follow, name='user_follow'),
    path('profile/<str:username>/', views.view_profile, name='view_profile'),
    path('most_followed_users/', views.most_followed_users, name='most_followed_users'),
    path('followed_users/', views.followed_users, name='followed_users'),
    path('activity_feed/', views.activity_feed, name='activity_feed'),
    path('all_messages/', views.all_messages, name='all_messages'),
    path('user_messages/<str:username>/', views.user_messages, name='user_messages'),
    path('send_messages/<str:username>/', views.send_messages, name='send_messages'),
    path('confirm_delete_messages/<str:username>/', views.user_messages_delete, name='confirm_delete_messages'),
    path('confirm_delete_messages/<str:username>/', views.user_messages_delete, name='confirm_delete_messages'),
    path('', include('django.contrib.auth.urls')),

]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from learning_logs.sitemaps import TopicSitemap

sitemaps = {
    'topics': TopicSitemap,
}

urlpatterns = [

    path('rex_pex_fex/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('learning_logs.api.urls', namespace='api')),
    path('account/', include('account.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('learning_logs.urls', namespace='learning_logs')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = 'learning_logs'

urlpatterns = [
    path('all_topics/', views.all_topics, name='all_topics'),
    # Page show all topics
    path('topics/', views.topics, name='topics'),
    path('tag/<slug:tag_slug>/', views.all_topics, name='topic_list_by_tag'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Adding new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # adding new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # editing the topic
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    # delete topic
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='confirm_delete_topic'),
    # delete comment
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='confirm_delete_entry'),
    # share
    path('<int:topic_id>/share/', views.share_post, name='share_post'),
    # search
    path('search/', views.topic_search, name='topic_search'),
    # topic like
    path('like/', views.topic_like, name='like'),
    # most liked topics
    path('most_liked_topics/', views.most_liked_topics, name='most_liked_topics'),
    # ranking topics
    path('most_viewed/', views.most_viewed, name='most_viewed'),
    # liked topics
    path('liked_topics/', views.liked_topics, name='liked_topics'),
    # api page
    path('api_page/', views.api_page, name='api_page'),
    # privacy policy
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    # contact
    path('contact/', views.contact_view, name='contact'),
    path('contact/success/', views.success_view, name='contact_success'),


    # Home page
    path('', views.index, name='index'),

]

actions/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


class Action(models.Model):
    user = models.ForeignKey('auth.User', related_name='actions', on_delete=models.CASCADE)
    verb = models.CharField(max_length=225)
    created = models.DateTimeField(auto_now_add=True)
    target_ct = models.ForeignKey(ContentType,
                                  blank=True,
                                  null=True,
                                  related_name='target_obj',
                                  on_delete=models.CASCADE)
    target_id = models.PositiveIntegerField(null=True, blank=True)
    target = GenericForeignKey('target_ct', 'target_id')

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['target_ct', 'target_id'])
        ]
        ordering = ['-created']

actions/views.py
from django.shortcuts import render

# Create your views here.

actions/templates/actions/action/detail.html
{% extends 'learning_logs/base.html' %}
<p>
  Check new activity:
</p>
{% with user=action.user profile=action.profile_user %}
<div class="action">
  <div class="images">
    {% if profile.photo %}
      <a href="{% url 'account:view_profile' user.id %}">
        <img src="{{ profile.photo.url }}" alt="{{ user.username }}" class="item-img">
      </a>
    {% endif %}
    {% if action.target %}
      {% with target=action.target %}
        {% if target.image %}
          <a href="{% url 'learning_logs:topic' target.id %}">
            <img src="{{ target.image.url }}" class="item-img">
          </a>
        {% endif %}
      {% endwith %}
    {% endif %}
  </div>
  <div class="info">
    <p>
      <span class="date">{{ action.created|timesince }} ago</span>
      <br />
      <a href="{% url 'account:view_profile' user.id %}">
        {{ user.first_name }}
      </a>
      {{ action.verb }}
      {% if action.target %}
        {% with target=action.target %}
          {% if action.verb == 'follow' %}
            <a href="{% url 'account:view_profile' target.id %}">{{ target.username }}</a>
          {% elif action.verb == 'liked' %}
            <a href="{% url 'learning_logs:topic' target.id %}">{{ target.text }}</a>
          {% elif action.verb == 'new_topic' %}
            <a href="{% url 'learning_logs:topic' target.id %}">{{ target.text }}</a>
          {% endif %}
        {% endwith %}
      {% endif %}
    </p>
  </div>
</div>
{% endwith %}